{"name": "Невозможно обновить данные пользователя, не используя авторизацию", "status": "passed", "description": "Проверяется: в теле ошибка == \"You should be authorised\" и статус код == 401.", "steps": [{"name": "Создание пользователя", "status": "passed", "start": 1723611896510, "stop": 1723611897263}, {"name": "Запись пользователя для очистки", "status": "passed", "start": 1723611897263, "stop": 1723611897263}, {"name": "Получение новых значений для пользователя", "status": "passed", "start": 1723611897263, "stop": 1723611897264}, {"name": "Отправка PATCH запроса для обновления пользователя без токена в заголовках", "status": "passed", "start": 1723611897264, "stop": 1723611897599}, {"name": "Проверка: в теле ответа message == 'You should be authorised'", "status": "passed", "start": 1723611897599, "stop": 1723611897599}, {"name": "Проверка: статус код == 401", "status": "passed", "start": 1723611897599, "stop": 1723611897599}], "start": 1723611896510, "stop": 1723611897609, "uuid": "5142e02d-c3f4-42ae-9da2-d22739cfa850", "historyId": "2d557b5c2f842e0fa3bdbb6cd4b8b49a", "testCaseId": "2d557b5c2f842e0fa3bdbb6cd4b8b49a", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_cannot_update_without_auth", "labels": [{"name": "suite", "value": "PATCH /api/auth/user"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "64295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}