{"name": "Невозможно войти в систему, используя даные несуществующего пользователя", "status": "passed", "description": "Для проверки создается и удаляется пользователь, под которым затем происходит попытка входа.Проверяется: в теле ошибка == \"email or password are incorrect\" и статус код == 401", "steps": [{"name": "Создание пользователя", "status": "passed", "start": 1723611892899, "stop": 1723611893352}, {"name": "Удаление пользователя", "status": "passed", "start": 1723611893352, "stop": 1723611894065}, {"name": "Отправка POST запроса для входа пользователя в систему", "status": "passed", "start": 1723611894066, "stop": 1723611894400}, {"name": "Проверка: в теле ошибка == 'email or password are incorrect'", "status": "passed", "start": 1723611894400, "stop": 1723611894400}, {"name": "Проверка: статус код == 401", "status": "passed", "start": 1723611894400, "stop": 1723611894400}], "start": 1723611892899, "stop": 1723611894400, "uuid": "34f78f6f-1d92-4f19-98f2-56e9d6aa005f", "historyId": "798a3c8cfa20acdee66b99685af8dc31", "testCaseId": "798a3c8cfa20acdee66b99685af8dc31", "fullName": "tests.test_user_login.TestUserLogin#test_login_user_non_existent_user_cannot_login", "labels": [{"name": "suite", "value": "POST /api/auth/login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "64295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}