{"name": "Невозможно создать пользователя, который уже зарегистрирован", "status": "passed", "description": "При выполнении теста один и тот же пользователь создается дважды. Проверяется: ошибка == \"User already exists\" и статус код == 403", "steps": [{"name": "Генерация данных для создания пользователя", "status": "passed", "start": 1723611886909, "stop": 1723611886910}, {"name": "Отправка POST запроса для создания пользователя", "status": "passed", "start": 1723611886910, "stop": 1723611887647}, {"name": "Запись пользователя для очистки", "status": "passed", "start": 1723611887647, "stop": 1723611887647}, {"name": "Отправка POST запроса для повторного создания того же пользователя", "status": "passed", "start": 1723611887647, "stop": 1723611888260}, {"name": "Проверка: ошибка == 'User already exists' при повторном создании", "status": "passed", "start": 1723611888260, "stop": 1723611888260}, {"name": "Проверка: код ответа == 403 при повторном создании", "status": "passed", "start": 1723611888260, "stop": 1723611888260}], "start": 1723611886909, "stop": 1723611888261, "uuid": "830358b0-fb7b-457f-aa13-e432bfe0315b", "historyId": "8d91de65cda001d04bdfe44b6d9e3254", "testCaseId": "8d91de65cda001d04bdfe44b6d9e3254", "fullName": "tests.test_user_create.TestUserCreation#test_create_user_only_unique_user_created", "labels": [{"name": "suite", "value": "POST /api/auth/register"}, {"name": "tag", "value": "@pytest.mark.usefixtures('cleanup_users')"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUserCreation"}, {"name": "host", "value": "C02DQ0GHMD6R"}, {"name": "thread", "value": "64295-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_create"}]}